name: Daily HackerNews to WhatsApp

on:
  schedule:
    - cron: '10 9 * * *'  # Runs daily at 9 AM IST
  workflow_dispatch:      # Allows manual trigger from GitHub

jobs:
  send-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Print environment variables for debugging
        run: |
          echo "TWILIO_ACCOUNT_SID is set: ${TWILIO_ACCOUNT_SID:+yes}"
          echo "TWILIO_AUTH_TOKEN is set: ${TWILIO_AUTH_TOKEN:+yes}"
          echo "TWILIO_WHATSAPP_NUMBER is set: ${TWILIO_WHATSAPP_NUMBER:+yes}"
          echo "TARGET_WHATSAPP_NUMBER is set: ${TARGET_WHATSAPP_NUMBER:+yes}"
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          TWILIO_WHATSAPP_NUMBER: ${{ secrets.FROM_WHATSAPP_NUMBER }}
          TARGET_WHATSAPP_NUMBER: ${{ secrets.TO_WHATSAPP_NUMBER }}

      - name: Run the script
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          TWILIO_WHATSAPP_NUMBER: ${{ secrets.FROM_WHATSAPP_NUMBER }}
          TARGET_WHATSAPP_NUMBER: ${{ secrets.TO_WHATSAPP_NUMBER }}
        run: python news_script.py

